### PR TITLE
Add ticket sales graph

### PR DESCRIPTION
**Pull request by ghost**
This graph was created using the following incantation in Jupyter.

``` python
import pandas as pd
import numpy as np
import matplotlib


matplotlib.style.use('ggplot')

data = pd.read_csv('attendees-anonymous.csv', parse_dates=[
        u'Ticket_Created_Date', 
        u'Ticket_Last_Updated_Date',
        u'Order_Created_Date',
        u'Order_Completed_Date'
   ])

data['count'] = pd.Series([1] * len(data), index=data.index)

%matplotlib inline

tickets = data[['Order_Created_Date', 'Ticket', 'count']]

tickets.set_index('Order_Created_Date').groupby('Ticket').resample('W', how='sum').reset_index().pivot(index='Order_Created_Date', columns='Ticket', values='count').fillna(0).plot(kind='area', figsize=(20,11))
```

​

​

### CODE REVIEW

**Comment by inglesp** [comment]
Hi @cjbarnes18, thanks for this.  That code's nice and short!

Could you make a couple of tweaks?

1) Could you add the code to a `scripts` directory in the codebase, so that we've got access to it in future?
2) We've got the same colour appearing for more than one ticket type.  Could you filter out the "Alt Party" and the "Conference Meal" ticket tickets -- these are less interesting than the other ticket types.  You could also remove "Django Girls / Transcode", since these tickets were all assigned on the same day, and you could maybe lump some of the smaller tickets (eg "Journalist", "Sprint Only") into an "Other" category.

Thank!

**Comment by Lukasa** [comment]
While we're here, let me give Travis a kick.

**Comment by ghost** [comment]
Ive been playing around with colour schemes, there is now a different colour for each ticket type. 
I can still trim down the tickets if you like.

**Comment by inglesp** [comment]
Thanks @cjbarnes18!

**Pull request merged**
