### PR TITLE
Add notes on how deployment works with Travis and IRL People

### PR DESCRIPTION
**Pull request by ghickman**
This explains how Travis is configured so it can deploy the website and how to recreate the necessary credentials if we need to.

### CODE REVIEW

**Comment by ghickman** [comment]
@doismellburning – would you mind having a quick look at this to see if they are good docs from a high level?

@meshy – would you mind checking this is enough information for you to recreate the current situation if you needed to for some reason?

**Comment by doismellburning** [comment]
LGTM

I don't want to bikeshed this (I'd happily merge this, but here also seems the best place to ask this question) but on the principle of "document as close to the thing as possible", do you think this might be better in the site repo, with a link there from internaldocs?

**Comment by meshy** [comment]
@ghickman seems clear to me. Links to the relevant code might be a nice bonus. Might be made a little easier by @doismellburning's suggestion.

**Comment by ghickman** [comment]
@doismellburning @meshy – updated to point to the docs in the website repo (which have been updated to include some of the text from my initial changes).

**Comment by doismellburning** [comment]
<3

**Comment by meshy** [comment]
:+1:

**Pull request merged**
