### PR TITLE
Add details of sponsorship packages

### PR DESCRIPTION
**Pull request by inglesp**
This comes out of discussions with @lifeisstillgood.  The only change is the number of free tickets we're offering with each sponsorship package -- I've increased the numbers after discussion with @doismellburning.

@evildmp, are you happy with the idea of a fifteen-minute "sponsored keynote" for gold sponsors?

### CODE REVIEW

**Comment by ghickman** [comment]
This all looks good to me. Will leave to @evildmp to sign off based on the question above.

**Comment by doismellburning** [comment]
Do we need this now?

This feels like a duplicate of the public site, and I feel like that should be the canonical version

**Comment by inglesp** [comment]
That's a good question.

I'm pretty keen to keep all documentation in one place, rather than split between here, the website, various Google forms, Twitter, etc.  Can we try to make this work?

**Comment by evildmp** [comment]
Sorry, missed that. No, not thrilled at the idea of sponsored keynotes, but since my reply's rather late...

**Comment by lifeisstillgood** [comment]
I have qualms too, but we are upping the sponsorship levels significantly and I wanted some "pizzazz" - and unfortunately could not think of anything that had some weight.  So it kind of stuck.

If anyone has a better idea it will be hard but not impossible to replace the offer (!) or if we have some means to mitigate (I was thinking of running a recruitment fair "conference" on the side where sponsored speakers were away from the main non-paid portion, but the logistics are basically twice the effort)

It is a concern - please shout.

PS
Hi ! :-)

## Yours

Paul Brian
paul@mikadosoftware.com
07540456115
@lifeisstillgood

> On 2 May 2016, at 16:31, Daniele Procida notifications@github.com wrote:
> 
> Sorry, missed that. No, not thrilled at the idea of sponsored keynotes, but since my reply's rather late...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

www.mikadosoftware.com

See your software improve with every change.

**Comment by inglesp** [comment]
It's on the website now, and I think it'll be fine as long as we clearly mark sponsored slots on the programme as being sponsored.

**Pull request merged**
